env:
  global:
    - SWIFT_BRANCH=development
    - SWIFT_VERSION=swift-DEVELOPMENT-SNAPSHOT-2018-12-04-a
matrix:
  include:
    - os: linux
      language: generic
      dist: trusty
      sudo: required
      addons:
        postgresql: 9.6
        apt:
          packages:
          - postgresql-9.6-postgis-2.3
      install:
        - sudo apt-get install clang libicu-dev
        - mkdir swift
        - curl https://swift.org/builds/$SWIFT_BRANCH/ubuntu1404/$SWIFT_VERSION/$SWIFT_VERSION-ubuntu14.04.tar.gz -s | tar xz -C swift &> /dev/null
        - export PATH="$(pwd)/swift/$SWIFT_VERSION-ubuntu14.04/usr/bin:$PATH"
      before_script:
        - psql -c 'create database postgis_tests;' -U postgres
      script:
        - swift package update
        - swift test

    - os: osx
      osx_image: xcode10
      language: swift
      sudo: required
      install:
        - brew install openssl
        - wget https://swift.org/builds/$SWIFT_BRANCH/xcode/$SWIFT_VERSION/$SWIFT_VERSION-osx.pkg
        - sudo installer -pkg $SWIFT_VERSION-osx.pkg -target /
        - export PATH="/Library/Developer/Toolchains/$SWIFT_VERSION.xctoolchain/usr/bin:$PATH"
      before_script:
        - export PG_DATA=$(brew --prefix)/var/postgres
        - pg_ctl -w start -l postgres.log --pgdata ${PG_DATA}
        - createuser -s postgres
        - psql -c 'create database postgis_tests;' -U postgres
        - cat postgres.log
      script:
        - swift package update
        - swift test
